CREATE TABLE [dbo].[Product]
(
    [ProductId] INT IDENTITY(1,1) NOT NULL,
    [ProductCode] NVARCHAR(50) NOT NULL,
    [SKU] NVARCHAR(100) NOT NULL CONSTRAINT [DF_Product_SKU] DEFAULT (N''),
    [Barcode] NVARCHAR(100) NULL,
    [ProductName] NVARCHAR(200) NOT NULL,
    [CategoryId] INT NOT NULL,
    [BrandId] INT NULL,
    [UnitId] INT NOT NULL,
    [CostPrice] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_Product_CostPrice] DEFAULT (0),
    [MinimumCost] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_Product_MinimumCost] DEFAULT (0),
    [VatPercentage] DECIMAL(9,4) NOT NULL CONSTRAINT [DF_Product_VatPercentage] DEFAULT (0),
    [VatAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_Product_VatAmount] DEFAULT (0),
    [MinimumSellingPrice] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_Product_MinimumSellingPrice] DEFAULT (0),
    [SellingPrice] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_Product_SellingPrice] DEFAULT (0),
    [WholesalePrice] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_Product_WholesalePrice] DEFAULT (0),
    [WholesaleMinQty] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_Product_WholesaleMinQty] DEFAULT (1),
    [TaxRate] DECIMAL(9,4) NOT NULL CONSTRAINT [DF_Product_TaxRate] DEFAULT (0),
    [DiscountAllowed] BIT NOT NULL CONSTRAINT [DF_Product_DiscountAllowed] DEFAULT (1),
    [IsStockTracked] BIT NOT NULL CONSTRAINT [DF_Product_IsStockTracked] DEFAULT (1),
    [MinimumStockLevel] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_Product_MinimumStockLevel] DEFAULT (0),
    [CurrentStock] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_Product_CurrentStock] DEFAULT (0),
    [ProductImageUrl] NVARCHAR(500) NOT NULL CONSTRAINT [DF_Product_ProductImageUrl] DEFAULT (N''),
    [Description] NVARCHAR(1000) NOT NULL CONSTRAINT [DF_Product_Description] DEFAULT (N''),
    [Status] NVARCHAR(30) NOT NULL CONSTRAINT [DF_Product_Status] DEFAULT (N'Active'),
    [IsActive] BIT NOT NULL CONSTRAINT [DF_Product_IsActive] DEFAULT (1),
    [CreatedByUserId] INT NULL,
    [UpdatedByUserId] INT NULL,
    [CreatedDate] DATETIME2(0) NOT NULL CONSTRAINT [DF_Product_CreatedDate] DEFAULT (SYSUTCDATETIME()),
    [UpdatedDate] DATETIME2(0) NULL,
    CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED ([ProductId] ASC),
    CONSTRAINT [FK_Product_Category] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[ProductCategory] ([CategoryId]),
    CONSTRAINT [FK_Product_Brand] FOREIGN KEY ([BrandId]) REFERENCES [dbo].[ProductBrand] ([BrandId]),
    CONSTRAINT [FK_Product_Unit] FOREIGN KEY ([UnitId]) REFERENCES [dbo].[ProductUnit] ([UnitId]),
    CONSTRAINT [UQ_Product_ProductCode] UNIQUE ([ProductCode]),
    CONSTRAINT [CK_Product_PricesNonNegative] CHECK ([CostPrice] >= 0 AND [MinimumCost] >= 0 AND [VatPercentage] >= 0 AND [VatAmount] >= 0 AND [MinimumSellingPrice] >= 0 AND [SellingPrice] >= 0 AND [WholesalePrice] >= 0 AND [WholesaleMinQty] >= 0),
    CONSTRAINT [CK_Product_SellingPriceMinimum] CHECK ([SellingPrice] >= [MinimumSellingPrice]),
    CONSTRAINT [CK_Product_StockNonNegative] CHECK ([MinimumStockLevel] >= 0 AND [CurrentStock] >= 0)
);
