:r ".\Seed\Authentication & User Management\AccessSeed.sql"
:r ".\Seed\Product Management\CategorySeed.sql"
:r ".\Seed\Product Management\UnitSeed.sql"
:r ".\Script\InventoryManagement.sql"
:r ".\Script\CustomerManagement.sql"
:r ".\Script\CustomerMemberModule.sql"
:r ".\Script\CustomerMultiMembershipDeployment.sql"
:r ".\Script\SalesManagement.sql"
:r ".\Seed\Customer Management\MemberLevelSeed.sql"
