CREATE PROCEDURE [dbo].[spCustomerHistoryGetRefundHistory] @CustomerId INT,@DateFrom DATETIME2=NULL,@DateTo DATETIME2=NULL,@PageNumber INT=1,@PageSize INT=20 AS
BEGIN
    SELECT CAST(NULL AS BIGINT) RefundId,CAST(NULL AS BIGINT) SaleId,CAST(NULL AS NVARCHAR(100)) SaleNo,CAST(NULL AS DATETIME2) RefundDate,CAST(0 AS DECIMAL(18,2)) RefundAmount,CAST(NULL AS NVARCHAR(500)) RefundReason,CAST(NULL AS NVARCHAR(30)) RefundStatus,CAST(NULL AS NVARCHAR(255)) CreatedByName,CAST(0 AS INT) TotalCount WHERE 1=0;
END
