CREATE TABLE [dbo].[SalesReturnHeader]
(
    [SalesReturnHeaderId] BIGINT IDENTITY(1,1) NOT NULL,
    [ReturnNo] NVARCHAR(50) NOT NULL,
    [SalesHeaderId] BIGINT NOT NULL,
    [ReturnDate] DATETIME2(0) NOT NULL CONSTRAINT [DF_SalesReturnHeader_ReturnDate] DEFAULT (SYSUTCDATETIME()),
    [CustomerId] INT NULL,
    [CashierUserId] INT NOT NULL,
    [RefundSubtotalAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesReturnHeader_RefundSubtotalAmount] DEFAULT (0),
    [RefundDiscountAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesReturnHeader_RefundDiscountAmount] DEFAULT (0),
    [RefundTaxAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesReturnHeader_RefundTaxAmount] DEFAULT (0),
    [RefundNetAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesReturnHeader_RefundNetAmount] DEFAULT (0),
    [Reason] NVARCHAR(500) NOT NULL,
    [Status] NVARCHAR(30) NOT NULL CONSTRAINT [DF_SalesReturnHeader_Status] DEFAULT (N'Draft'),
    [ApprovedByUserId] INT NULL,
    [ApprovedDate] DATETIME2(0) NULL,
    [CreatedByUserId] INT NULL,
    [UpdatedByUserId] INT NULL,
    [CreatedDate] DATETIME2(0) NOT NULL CONSTRAINT [DF_SalesReturnHeader_CreatedDate] DEFAULT (SYSUTCDATETIME()),
    [UpdatedDate] DATETIME2(0) NULL,
    CONSTRAINT [PK_SalesReturnHeader] PRIMARY KEY CLUSTERED ([SalesReturnHeaderId]),
    CONSTRAINT [UQ_SalesReturnHeader_ReturnNo] UNIQUE ([ReturnNo]),
    CONSTRAINT [FK_SalesReturnHeader_SalesHeader] FOREIGN KEY ([SalesHeaderId]) REFERENCES [dbo].[SalesHeader] ([SalesHeaderId]),
    CONSTRAINT [FK_SalesReturnHeader_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer] ([CustomerId]),
    CONSTRAINT [FK_SalesReturnHeader_Cashier] FOREIGN KEY ([CashierUserId]) REFERENCES [dbo].[AccessUser] ([UserId]),
    CONSTRAINT [FK_SalesReturnHeader_ApprovedBy] FOREIGN KEY ([ApprovedByUserId]) REFERENCES [dbo].[AccessUser] ([UserId]),
    CONSTRAINT [CK_SalesReturnHeader_Status] CHECK ([Status] IN (N'Draft',N'Approved',N'Rejected',N'Completed',N'Cancelled')),
    CONSTRAINT [CK_SalesReturnHeader_Amounts] CHECK ([RefundSubtotalAmount] >= 0 AND [RefundDiscountAmount] >= 0 AND [RefundTaxAmount] >= 0 AND [RefundNetAmount] >= 0)
);
