CREATE TABLE [dbo].[SalesHeader]
(
    [SalesHeaderId] BIGINT IDENTITY(1,1) NOT NULL,
    [SaleNo] NVARCHAR(50) NOT NULL,
    [SaleDate] DATETIME2(0) NOT NULL CONSTRAINT [DF_SalesHeader_SaleDate] DEFAULT (SYSUTCDATETIME()),
    [CustomerId] INT NULL,
    [CashierUserId] INT NOT NULL,
    [SubtotalAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesHeader_SubtotalAmount] DEFAULT (0),
    [ItemDiscountAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesHeader_ItemDiscountAmount] DEFAULT (0),
    [OrderDiscountAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesHeader_OrderDiscountAmount] DEFAULT (0),
    [TotalDiscountAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesHeader_TotalDiscountAmount] DEFAULT (0),
    [TaxAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesHeader_TaxAmount] DEFAULT (0),
    [NetAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesHeader_NetAmount] DEFAULT (0),
    [PaidAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesHeader_PaidAmount] DEFAULT (0),
    [ChangeAmount] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_SalesHeader_ChangeAmount] DEFAULT (0),
    [Status] NVARCHAR(30) NOT NULL CONSTRAINT [DF_SalesHeader_Status] DEFAULT (N'Completed'),
    [Remark] NVARCHAR(1000) NOT NULL CONSTRAINT [DF_SalesHeader_Remark] DEFAULT (N''),
    [CreatedByUserId] INT NULL,
    [UpdatedByUserId] INT NULL,
    [CreatedDate] DATETIME2(0) NOT NULL CONSTRAINT [DF_SalesHeader_CreatedDate] DEFAULT (SYSUTCDATETIME()),
    [UpdatedDate] DATETIME2(0) NULL,
    CONSTRAINT [PK_SalesHeader] PRIMARY KEY CLUSTERED ([SalesHeaderId]),
    CONSTRAINT [UQ_SalesHeader_SaleNo] UNIQUE ([SaleNo]),
    CONSTRAINT [FK_SalesHeader_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer] ([CustomerId]),
    CONSTRAINT [FK_SalesHeader_Cashier] FOREIGN KEY ([CashierUserId]) REFERENCES [dbo].[AccessUser] ([UserId]),
    CONSTRAINT [FK_SalesHeader_CreatedBy] FOREIGN KEY ([CreatedByUserId]) REFERENCES [dbo].[AccessUser] ([UserId]),
    CONSTRAINT [FK_SalesHeader_UpdatedBy] FOREIGN KEY ([UpdatedByUserId]) REFERENCES [dbo].[AccessUser] ([UserId]),
    CONSTRAINT [CK_SalesHeader_Status] CHECK ([Status] IN (N'Completed',N'PartiallyRefunded',N'Refunded',N'Voided')),
    CONSTRAINT [CK_SalesHeader_Amounts] CHECK ([SubtotalAmount] >= 0 AND [ItemDiscountAmount] >= 0 AND [OrderDiscountAmount] >= 0 AND [TotalDiscountAmount] >= 0 AND [TaxAmount] >= 0 AND [NetAmount] >= 0 AND [PaidAmount] >= 0 AND [ChangeAmount] >= 0)
);
